# Q-Learning
TRANSFORMED_BELLMAN: bool = True
DISCOUNT: float = 0.99
EPSILON_HIGH: float = 0.5
EPSILON_LOW: float = 0.1
EPSILON_DECAY: float = 8e-4
REWARD_SCALING: float = 5.
TARGET_UPDATE_INTERVAL: int = 1_500
# Deep
LEARNING_RATE: float = 3e-4
BATCH_SIZE: int = 64
# Buffer
REPLAY_CAPACITY: int = 2**19
PER_BETA_INCREMENT: float = 5e-4
PRIORITY_MEAN_MAX: float = 0.9
PRIORITY_ALPHA: float = 0.9
PRIORITY_BETA: float = 0.6
MIN_REPLAY_LEN: int = 4_000
# Extras
N_STEPS: int = 3
NUM_QUANTILES: int = 50
RECURRENT_STEPS: int = 30
BURN_IN_STEPS: int = 10
